---
- name: "Installing LEMP on ubuntu"
  hosts: ubuntu
  become: yes
  vars_files:
    - packages-nginx-php.vars
    - secret.vars
    - nginx-conf.vars
    - mariadb-wordpress.vars
  tasks:
    - name: "Nginx and php8.1-fpm and extensions Installation"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      register: package
      
    - name: "restart/enable-nginx-php8.1-fpm"
      when: package.changed == true
      service:
        enabled: yes
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - php8.1-fpm
        
    - name: "Creating Document root /var/www/{{ domain_name}}"
      file:
        group: "{{ nginx_group }}"
        owner: "{{ nginx_user }}"
        path: "/var/www/{{ domain_name }}"
        state: directory


    - name: "Creating nginx conf /etc/nginx/sites-available/{{ domain_name }}.conf"
      template:
        dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
        src: vhost.tmpl
      register: vhostavailable

    - name: "Enabling nginx conf /etc/nginx/sites-available/{{ domain_name }}.conf"
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}.conf"
        state: link
        path: "/etc/nginx/sites-enabled/{{ domain_name }}.conf"
      register: vhostenable

    - name: "restart/enable-nginx-php8.1-fpm"
      when: vhostavailable.changed == true or vhostenable == true
      service:
        enabled: yes
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - php8.1-fpm

    - name: "Copying info.php file"
      copy:
        dest: "/var/www/{{ domain_name }}"
        src: "{{ item }}"
        group: "{{ nginx_group }}"
        owner: "{{ nginx_user }}"
      with_items:
        - info.php
        - info.html
        - test.html
        - fifth.html
        
        
    - name: " Installing Mariadb Packages and python3-pip"
      apt:
        name:
          - mariadb-server
          - python3-pip
        state: present
        update_cache: yes
    
    - name: "restart/enable Mariadb-server"
      service:
        name: mariadb
        state: restarted
        enabled: yes
    - name: "Python connector/module Installation"
      pip:
        name: PyMySQL
        state: present

    - name: "Resetting Mariadb root Password"
      ignore_errors: yes
      mysql_user:
        host_all: yes
        login_unix_socket: /run/mysqld/mysqld.sock
        login_password: ""
        login_user: root
        name: root 
        password: "{{ maria_root_pwd }}"
            
            
    - name: "Creating Mariadb database for wordpress"
      mysql_db:
        login_password: "{{ maria_root_pwd }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: root
        name: "{{ maria_db }}"
        state: present


    
    - name: "Creating mariadb user for wp with privilege"
      no_log: true
      mysql_user:
        host: "%"
        login_password: "{{ maria_root_pwd }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: root
        name: "{{ maria_user }}"
        password: "{{ maria_pwd }}"
        priv: '{{ maria_db }}.*:ALL'
        state: present
